baseURL = 'https://blog.uta8a.net/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'diaryです'
theme = 'suuri'

[markup.goldmark.renderer]
hardWraps = true # 改行でbrを入れる
unsafe = true # Markdown中のHTMLタグをrender

[markup.highlight]
noClasses = false # disable injecting style for syntax highlight
